Sprint7
ClevertecFrontendLab/Krautsou-Andrei pull request #5
Opened 2023-03-26 22:11 UTC by Krautsou-Andrei

2023-03-26 22:49 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 94%.
Общее количество тестов: 98.
Количество непройденных тестов: 5.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/23-1440-profile-expider-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check cancel booking success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20cancel%20booking%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- expired -- expired-handed (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679870997/Sprint%207%20--%20Profile%20functions%20tests%20--%20expired%20--%20expired-handed%20(failed).png)

2023-03-26 23:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/23-1440-profile-expider-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- expired -- expired-handed (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679873211/Sprint%207%20--%20Profile%20functions%20tests%20--%20expired%20--%20expired-handed%20(failed).png)

2023-03-27 00:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/23-1440-profile-expider-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- expired -- expired-handed (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679875721/Sprint%207%20--%20Profile%20functions%20tests%20--%20expired%20--%20expired-handed%20(failed).png)

2023-03-27 00:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/23-1440-profile-expider-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- delivery-book-test -- has-back-date (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/Sprint%207%20--%20Profile%20functions%20tests%20--%20delivery-book-test%20--%20has-back-date%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- expired -- expired-handed (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679876793/Sprint%207%20--%20Profile%20functions%20tests%20--%20expired%20--%20expired-handed%20(failed).png)

2023-03-27 00:27 UTC, Krautsou-Andrei commented
Код очень плохой. Сам это понимаю. Не тратьте время на проверку. Это мой первый проект. Реакт и все что делал увидел на этом проекте впервые. Лучшей благодарностью за мои старания будет экскурсия в офис компании и знакомство с командой, создавшей и сопровождающей нас на этом проекте. Спасибо вам я получил огромный опыт и кучу эмоций)

2023-03-27 05:51 UTC, dariavorom requested changes

2023-03-27 05:51 UTC, dariavorom commented on src/pages/components/profil/empty-card/empty-card.jsx
> +      {/* Забронируйте книгу <br />и она отобразится */}
удалить все комменты по коду

2023-03-27 05:51 UTC, dariavorom commented on src/pages/components/profil/empty-card/empty-card.jsx
> +export const EmptyCard = ({ title, style }) => (
текст по макету не на всю ширину 
![image](https://user-images.githubusercontent.com/64946271/227849527-583fc534-3e18-4668-9286-f9a51184724b.png)
![image](https://user-images.githubusercontent.com/64946271/227849714-21d28db6-5bbd-4fc5-9913-255596654557.png)
![image](https://user-images.githubusercontent.com/64946271/227849584-e1ca6e30-2746-423f-be46-489eed43ba0c.png)

2023-03-27 05:51 UTC, dariavorom commented on src/pages/components/profil/profil-user/profil-user.jsx
> +import classNames from 'classnames';
поправить верстку, по умолчанию пароль заполнен звездочками 
![image](https://user-images.githubusercontent.com/64946271/227850713-9ebf259f-471c-44f3-84dd-31a1b6c66e4a.png)
![image](https://user-images.githubusercontent.com/64946271/227850461-2a48d4e9-6f16-48cc-b620-dd011dee90c7.png)
![image](https://user-images.githubusercontent.com/64946271/227850538-642a09bc-e9ae-4033-9fc0-180650ef223e.png)

2023-03-27 05:51 UTC, dariavorom commented on src/data/data-burger-link/data-burger-link.jsx
> +    { id: 'burger-1', link: '/profile', title: 'Профиль', dataTest: 'true', dataTestLink: 'profile-button' },
все роуты нужно было вынести давно в констату в отдельный файл

2023-03-27 05:51 UTC, dariavorom commented on src/helpers/error-helper-for-input.js
> +// import style from '../pages/components/form-enter/form-enter.module.scss';
много закомментированного кода по проекту - удалить

2023-03-27 09:26 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 96%.
Общее количество тестов: 98.
Количество непройденных тестов: 3.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/23-1440-profile-expider-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**Sprint 6 -- booking and book rate -- books rating -- check rate modal elements (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/Sprint%206%20--%20booking%20and%20book%20rate%20--%20books%20rating%20--%20check%20rate%20modal%20elements%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- expired -- expired-handed (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679909217/Sprint%207%20--%20Profile%20functions%20tests%20--%20expired%20--%20expired-handed%20(failed).png)

2023-03-27 09:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 97%.
Общее количество тестов: 98.
Количество непройденных тестов: 2.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/23-1440-profile-expider-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/9-app%20-burger-menu-close-768px.png)
***
**Sprint 6 -- booking and book rate -- booking edit modal -- check edit booking request success (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/Sprint%206%20--%20booking%20and%20book%20rate%20--%20booking%20edit%20modal%20--%20check%20edit%20booking%20request%20success%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- expired -- expired-handed (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Krautsou-Andrei/1679910376/Sprint%207%20--%20Profile%20functions%20tests%20--%20expired%20--%20expired-handed%20(failed).png)

2023-03-27 10:06 UTC, dariavorom approved these changes

2023-03-27 10:46 UTC, ValadzkoAliaksei approved these changes

2023-03-27 10:48 UTC, merged